---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: golang
  commands:
  - go test -cover ./...
  - go install honnef.co/go/tools/cmd/staticcheck@latest
  - "`go env GOPATH`/bin/staticcheck ./..."

trigger:
  event:
    include:
      - push
      - pull_request
---
hmac: "3578aa331afc59fb761a53431e3886221fae525ada6b31ddcba805d81bb73236"
kind: signature
...
