name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Run go test
        run: go test -cover ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: |
          chown -R root:root .
          staticcheck ./...
